---
abstract: 'like ref() but useful'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
  Test::NoWarnings: 0
  Test::Requires: 0.06
  URI: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 1
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Scalar-Does
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  IO::Detect:
    file: lib/IO/Detect.pm
    version: 0.201
  IO::Detect::SmartMatcher:
    file: lib/IO/Detect.pm
    version: 0.201
  Scalar::Does:
    file: lib/Scalar/Does.pm
    version: 0.201
  Scalar::Does::MooseTypes:
    file: lib/Scalar/Does/MooseTypes.pm
    version: 0.201
  Scalar::Does::RoleChecker:
    file: lib/Scalar/Does.pm
    version: 0.201
requires:
  Exporter::Tiny: 0.026
  Scalar::Util: 1.24
  Type::Tiny: 0.004
  URI::file: 0
  lexical::underscore: 0
  namespace::clean: 0.19
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Scalar-Does/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Scalar-Does
  homepage: https://metacpan.org/release/Scalar-Does
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-scalar-does
version: 0.201
