---
abstract: 'like ref() but useful'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Scalar::Does
name: Scalar-Does
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  IO::Detect: 0.001
  Scalar::Util: 1.20
  Sub::Exporter: 0
  namespace::clean: 0.19
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Scalar-Does
  homepage: https://metacpan.org/release/Scalar-Does
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-scalar-does
version: 0.003
